### ISSUE TITLE
JSONDecoder Error

### ISSUE THREAD

**Issue by fvlasie** [mdolr/bloom-chatbot#1]
Hello! 

I am trying to run your bot on MacOS but i get the following error after I enter text for User:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/requests/models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/Cellar/python@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/local/Cellar/python@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/Cellar/python@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/admin/Downloads/bloom-chatbot-main/main.py", line 128, in <module>
    initialize(config)
  File "/Users/admin/Downloads/bloom-chatbot-main/main.py", line 125, in initialize
    discussion(config, prompts, seed)
  File "/Users/admin/Downloads/bloom-chatbot-main/main.py", line 77, in discussion
    bot_response = generate_response(config, full_prompt, seed)
  File "/Users/admin/Downloads/bloom-chatbot-main/main.py", line 43, in generate_response
    resp = infer(f"{full_prompt}\n{config.BOT_NAME}: ", seed)
  File "/Users/admin/Downloads/bloom-chatbot-main/src/inference.py", line 43, in infer
    response = inference(prompt, params=params)
  File "/usr/local/lib/python3.10/site-packages/huggingface_hub/inference_api.py", line 162, in __call__
    ).json()
  File "/usr/local/lib/python3.10/site-packages/requests/models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

Any guidance would be much appreciated!

Thank you! This looks like an interesting project and I am eager to try it out.

:)

**Comment by mdolr** [comment]
Hey!

It's probably due to Hugging Face API having been updated I'll take a look into it

**Comment by mdolr** [comment]
Ok actually I think you just choosed a really unfortunate timing to try the bot, the inference API seems to be down even on the official page https://huggingface.co/bigscience/bloom when you try to run the example

**Comment by fvlasie** [comment]
Thank you for checking! Merci beaucoup !

**Comment by mdolr** [comment]
Hey @fvlasie I've checked again today, the API seems to be working again and I tried the bot it works as well so you can try it on your own 😄 let me know if you encouter other issues! I'll close this one for now
